server:
  port: 8080

spring:
  datasource:
    drive-class-name: com.mysql.jdbc.Driver
    username: "root"
    password:
    url: jdbc:mysql://localhost:3306/customer_management_db

  jpa:
    hibernate:
      ddl-auto: create-drop