server:
  port: 8085

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
  datasource:
    drive-class-name: com.mysql.jdbc.Driver
    username: "user"
    password: "pass"
    url: "jdbc:mysql://localhost:3306/orderManagementDb"

  jpa:
    hibernate:
      ddl-auto: create-drop

estoque:
  client:
    url: http://localhost:8081/estoque

pagamento:
  client:
    url: http://localhost:8083/pagamento