apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastfood-order-management-mysql-statefulset
  labels:
    app: fastfood-order-mananagement-mysql
spec:
  replicas: 1
  template:
    metadata:
      name: fastfood-order-management-mysql
      labels:
        app: fastfood-order-management-mysql
    spec:
      containers:
        - name: fastfood-order-management-mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-mysql-secret-opaque
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-mysql-secret-opaque
                  key: MYSQL_DATABASE
  selector:
    matchLabels:
      app: fastfood-order-management-mysql
  serviceName: fastfood-order-management-mysql-service
