apiVersion: v1
kind: Secret
metadata:
  name: fastfood-order-management-secret-opaque
type: Opaque
stringData:
  MYSQL_HOST: fastfood-order-management-mysql-service
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
  MYSQL_DB: customer_management_db
