apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-order-management-deployment
  labels:
    app: fastfood-order-management
spec:
  replicas: 1
  template:
    metadata:
      name: fastfood-order-management
      labels:
        app: fastfood-order-management
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: fastfood-order-management-container
          image: soatpostech/fastfood-order-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: MYSQL_HOST

            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: MYSQL_USERNAME

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: MYSQL_PASSWORD

            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: RABBIT_HOST

            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: RABBIT_USERNAME

            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: RABBIT_PASSWORD

            - name: PRODUCT_MANAGEMENT_URL
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: PRODUCT_MANAGEMENT_URL

            - name: PRODUCTION_URL
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: PRODUCTION_URL

            - name: PAYMENT_URL
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: PAYMENT_URL

            - name: DISCOVERY_SERVER
              valueFrom:
                secretKeyRef:
                  name: fastfood-order-management-secret-opaque
                  key: DISCOVERY_SERVER

#            - name: MYSQL_DB
#              valueFrom:
#                secretKeyRef:
#                  name: fastfood-product-management-secret-opaque
#                  key: MYSQL_DB

#          livenessProbe:
#            httpGet:
#              path: /actuator/health/
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
#            initialDelaySeconds: 30
#          readinessProbe:
#             httpGet:
#               path: /actuator/health
#               port: 8080
#             periodSeconds: 10
#             failureThreshold: 5
#             initialDelaySeconds: 10
#          resources:
#            requests:
#              cpu: 10m
  selector:
    matchLabels:
      app: fastfood-order-management
