apiVersion: v1
kind: Secret
metadata:
  name: fastfood-order-management-secret-opaque
type: Opaque
stringData:
  MYSQL_HOST: fastfood-order-management-mysql-service
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
  MYSQL_DB: customer_management_db
  RABBIT_HOST: fastfood-production-rabbit-service
  RABBIT_USERNAME: product-production
  RABBIT_PASSWORD: product-production-123
  PRODUCT_MANAGEMENT_URL: http://fastfood-product-management-service:8081
  PRODUCTION_URL: http://fastfood-production-service:8082
  PAYMENT_URL: http://fastfood-payment-service:8083
  DISCOVERY_SERVER: spring-cloud-kubernetes-discoveryserver
